# Generated by Django 5.2.17 on 2026-09-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'capabilities',
                'permissions': [('view_directory', 'See the member directory'), ('view_member_records', "Open a member's page, with their contact details and standing"), ('invite_members', 'Send invitations and manage entry links'), ('set_club_position', "Set another member's club position"), ('edit_member_privileges', "Edit another member's category, name, and student details"), ('assign_groups', 'Decide which groups an account is in'), ('manage_groups', 'Create and change the groups themselves'), ('issue_temporary_password', 'Issue a one-time password for someone who cannot get in'), ('archive_members', 'Archive a member who has left, and bring one back'), ('view_archive', 'Read the archive of former members'), ('delete_accounts', 'Delete an account outright'), ('impersonate_members', 'View the site as another member, read-only'), ('override_license', 'Override a licence class, status, or expiry'), ('approve_agreements', 'Approve a signed access agreement, and revoke an approval'), ('convert_minor_accounts', "Convert a member's account to an adult's at 18"), ('rotate_shared_secret', 'Set or rotate the computer password'), ('create_events', 'Create an event and import from the calendar'), ('manage_events', 'Edit any event, its slots, and its captains'), ('manage_signups', "Move, remove, or check in another person's sign-up"), ('view_participant_contacts', 'See the phone and email of people on a roster'), ('send_announcements', 'Send an announcement to members'), ('view_outbox', 'Read the outbox of everything the site has sent'), ('view_reports', 'View and export participation, hours, and credential reports'), ('view_audit_log', 'Read the audit log'), ('edit_club_settings', "Edit the club's configuration and message templates"), ('view_job_status', 'See the scheduled jobs and their last runs')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
