# Generated by Django 5.2.17 on 2026-09-13 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='contest', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description_html', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('locked', 'Locked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
                ('display_timezone', models.CharField(blank=True, max_length=60)),
                ('min_license_class', models.CharField(blank=True, max_length=20)),
                ('rules_url', models.URLField(blank=True)),
                ('contest_fields', models.JSONField(blank=True, default=dict)),
                ('calendar_ref', models.PositiveIntegerField(blank=True, null=True)),
                ('kbyg_html', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL)),
                ('duplicated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='events.event')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_club_station', models.BooleanField(default=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('is_private_residence', models.BooleanField(default=False)),
                ('directions_html', models.TextField(blank=True)),
                ('kbyg_html', models.TextField(blank=True)),
                ('viability_rule', models.JSONField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='events.event')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('opens_at', models.DateTimeField()),
                ('categories', models.JSONField(blank=True, default=list)),
                ('announce', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openings', to='events.event')),
            ],
            options={
                'ordering': ['opens_at'],
            },
        ),
        migrations.CreateModel(
            name='OperatingLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_hours_per_day', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('day_basis', models.CharField(choices=[('utc', 'UTC day'), ('local', 'Local day')], default='utc', max_length=5)),
                ('max_total_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('min_break_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limit', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='OperatingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='events.event')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Station', max_length=60)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='events.location')),
            ],
            options={
                'ordering': ['location__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ResponsibleAdult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('present_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_adults', to='events.signup')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('kind', models.CharField(default='operating', max_length=20)),
                ('closed', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('control_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='events.position')),
            ],
            options={
                'ordering': ['start', 'position__location__order', 'position__order'],
            },
        ),
        migrations.AddField(
            model_name='signup',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='events.slot'),
        ),
        migrations.CreateModel(
            name='EligibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('min_license_class', models.CharField(blank=True, max_length=20)),
                ('required_credentials', models.JSONField(blank=True, default=list)),
                ('minors_allowed', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_rules', to='events.event')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_rules', to='events.slot')),
            ],
        ),
        migrations.CreateModel(
            name='Captaincy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captaincies', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captaincies', to='events.event')),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='signup',
            unique_together={('slot', 'user')},
        ),
        migrations.CreateModel(
            name='RoleCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('capacity', models.PositiveSmallIntegerField(default=1)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to='events.slot')),
            ],
            options={
                'unique_together': {('slot', 'role')},
            },
        ),
    ]
