# Generated by Django 5.2.17 on 2026-09-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='no_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='min_license_class',
            field=models.CharField(blank=True, max_length=20, verbose_name='preferred license class'),
        ),
    ]
