# Generated by Django 5.2.17 on 2026-09-15 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_entry_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reminder_hours_before',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Blank uses the club default (FR-72).', null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='no_show_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SlotWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_key', models.CharField(max_length=200)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='events.slot')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
