# Generated by Django 5.2.17 on 2026-09-15 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_reminders_warnings_no_show'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='display_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_text',
            field=models.CharField(blank=True, help_text="For display-only events: 'Tuesdays 20:00 ET'.", max_length=120),
        ),
        migrations.AddField(
            model_name='opening',
            name='announced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('state', models.CharField(choices=[('pending', 'Waiting'), ('offered', 'Offered'), ('accepted', 'Accepted'), ('expired', 'Offer expired'), ('withdrawn', 'Withdrawn')], default='pending', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('offered_at', models.DateTimeField(blank=True, null=True)),
                ('offer_expires_at', models.DateTimeField(blank=True, null=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='events.slot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'unique_together': {('slot', 'user', 'role')},
            },
        ),
    ]
