# Generated by Django 5.2.17 on 2026-09-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_display_only_waitlist_openings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reminder_hours_before',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Blank uses the club default.', null=True),
        ),
    ]
