# Generated by Django 5.2.17 on 2026-09-15 15:47

import secrets

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_place_sign_in_email"),
        ("events", "0002_entry_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("sysadmin", "Sysadmin"),
                    ("officer", "Club officer"),
                    ("member", "Member"),
                    ("provisional", "Provisional"),
                    ("none", "No access"),
                ],
                default="none",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="EntryLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("class", "Class (institution addresses, admitted at once)"),
                            ("community", "Community (anyone, admitted as Provisional)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("required_domain", models.CharField(blank=True, max_length=120)),
                (
                    "token",
                    models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True),
                ),
                ("expires_at", models.DateTimeField()),
                ("cap", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=8,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entry_links_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "landing_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="joined_via",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="joined",
                to="accounts.entrylink",
            ),
        ),
    ]
