# Generated by Django 5.2.17 on 2026-09-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_entry_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='push_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
