# Generated by Django 5.2.17 on 2026-09-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_push_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_uls_name',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
