# Generated by Django 5.2.17 on 2026-09-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_pending_uls_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="closure_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="legal_hold",
            field=models.BooleanField(default=False),
        ),
    ]
