# Generated by Django 5.2.17 on 2026-09-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_closure_deletion_legal_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sign_in_only_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
