# Generated by Django 5.2.17 on 2026-09-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_identity_is_a_key_addresses_are_rows"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("sysadmin", "Sysadmin"),
                    ("advisor", "Faculty advisor"),
                    ("officer", "Club officer"),
                    ("member", "Member"),
                    ("provisional", "Provisional"),
                    ("none", "No access"),
                ],
                default="none",
                max_length=12,
            ),
        ),
    ]
