# Generated by Django 5.2.17 on 2026-09-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_faculty_advisor_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='archived_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
