# Generated by Django 5.2.17 on 2026-09-17 12:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_capabilities_and_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="access_level",
        ),
    ]
