# Generated by Django 5.2.17 on 2026-09-19 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_the_suspended(apps, schema_editor):
    """An account with no access and no closure request was suspended by somebody.

    The fact was only in the audit log until now (§2.3, 2026-09-19). Where the log still has the
    row, the date, the actor and the reason come back with it; where it does not, the account is
    marked suspended without them rather than passing for Active.
    """
    User = apps.get_model("accounts", "User")
    AuditLog = apps.get_model("ops", "AuditLog")
    for user in User.objects.filter(
        closure_requested_at__isnull=True, suspended_at__isnull=True, deleted_at__isnull=True
    ):
        if user.is_superuser or user.groups.exists():
            continue
        row = (
            AuditLog.objects.filter(action="access.changed", subject_id=str(user.pk))
            .order_by("-at")
            .first()
        )
        user.suspended_at = row.at if row else user.date_joined
        user.suspended_by = row.actor if row and row.actor_id else None
        user.suspended_reason = ((row.after or {}).get("reason", "") if row else "")[:200]
        user.save(update_fields=["suspended_at", "suspended_by", "suspended_reason"])


def forget_the_suspended(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.update(suspended_at=None, suspended_by=None, suspended_reason="")


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0001_initial"),
        ('accounts', '0014_officers_appoint_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='suspended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='suspended_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RunPython(mark_the_suspended, forget_the_suspended),
    ]
