# Generated by Django 5.2.17 on 2026-09-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_advisors_set_category_and_appoint_peers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
