# Generated by Django 5.2.17 on 2026-09-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_advisors_rotate_the_computer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='proof',
            field=models.CharField(blank=True, choices=[('mailbox', 'Opened a link sent to it'), ('officer', 'Confirmed by an officer'), ('vouched', 'Vouched for when the account was made')], max_length=10),
        ),
    ]
