# Generated by Django 5.2.17 on 2026-09-20 23:06

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_how_an_address_was_proved'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='mail_token',
            field=models.CharField(blank=True, default=secrets.token_urlsafe, max_length=64),
        ),
    ]
