# Generated by Django 5.2.17 on 2026-09-13 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('body_html', models.TextField()),
                ('variables', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.JSONField(default=dict)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('subject', models.CharField(max_length=200)),
                ('body_html', models.TextField()),
                ('sent_outside', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='events.event')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_addresses', models.JSONField(default=list)),
                ('channel', models.CharField(default='email', max_length=10)),
                ('category', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=200)),
                ('body_html', models.TextField()),
                ('body_text', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('not_sent', 'Not sent (email off)'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('outside', 'Sent outside the system')], default='not_sent', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'outbox',
                'ordering': ['-created'],
            },
        ),
    ]
