# Generated by Django 5.2.17 on 2026-09-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='outbox',
            name='state',
            field=models.CharField(choices=[('not_sent', 'Not sent (email off)'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('outside', 'Sent outside the system'), ('skipped', 'Not emailed (preference off)')], default='not_sent', max_length=10),
        ),
    ]
