# Generated by Django 5.2.17 on 2026-09-15 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0002_template_edited_and_skipped_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='announcement',
            name='recipients',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='outbox',
            name='announcement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='comms.announcement'),
        ),
        migrations.AddField(
            model_name='outbox',
            name='reply_to',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
