# Generated by Django 5.2.17 on 2026-09-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credentials", "0003_resign_by_notices_revoked"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenserecord",
            name="licensee_type",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="ulslicense",
            name="applicant_type",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="ulsstaging",
            name="applicant_type",
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
