# Generated by Django 5.2.17 on 2026-09-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0004_license_applicant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ulslicense',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='ulsstaging',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
