# Generated by Django 5.2.17 on 2026-09-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0008_the_seeded_rows_name_a_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialdecision',
            name='seeded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signedagreement',
            name='pdf_built_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
