# Generated by Django 5.2.17 on 2026-09-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0010_the_by_column_is_a_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='signedagreement',
            name='pdf_render_version',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
