# Generated by Django 5.2.17 on 2026-09-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0011_a_pdf_knows_which_rendering_made_it'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialdecision',
            name='action',
            field=models.CharField(choices=[('approved', 'Approved'), ('approved_after_decline', 'Approved on reversal'), ('declined', 'Declined'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('superseded', 'Superseded by a new version')], max_length=24),
        ),
    ]
